use_wandb: False
use_sky: False
use_dynamic: False
use_pose_refine: False

mode: 'vio' # 'vo' or 'vio'


device:
  tracker: 'cuda:0'
  mapper: 'cuda:0'

dataset:
  root: /data/wuke/DATA/2024/RAW_KITTI/2011_09_30/2011_09_30_drive_0027_sync/
  module: datasets.kitti_sync
  rgb_strip: 1
  imu_delay: 0.09

middleware:
  cov_times: 300000
  max_cov: 2e4 # 1e5
  max_depth: 30

output:
  save_dir: /data/wuke/workspace/VINGS-Mono/output/

# 707.0912 707.0912 601.8873 183.1104
intrinsic:
  H: 370
  W: 1226
  fu: 707.0912
  fv: 707.0912
  cu: 183.1104
  cv: 601.8873
  bg: 0

frontend:
  weight: /data/wuke/workspace/VINGS-Mono/ckpts/droid.pth
  image_size: [344, 616] # [240, 800]
  buffer: 80
  filter_thresh: 2.4
  c2i: None
  # visual_only: 0 # 0 means VIO and 1 means VO.
  warm_up: 8
  beta: 0.3
  frontend_nms: 1
  keyframe_thresh: 4.0
  frontend_window: 5
  frontend_thresh: 16.0 
  frontend_radius: 2
  active_window: 12
  # CovisibleGraph
  max_factors: 48
  far_threshold: 0.02
  inac_range: 3
  mask_threshold: -1.0
  skip_edge: [-4,-5,-6]
  translation_threshold: 0.5
  # Vis.
  show_plot: False

adc_args:
  accum_thresh: 0.98
training_args:
  num_keyframe: 8
  iters: 200
  lr: # Copy form 2DGS.
    _xyz_lr: 0.0001
    _rgb_lr: 0.00001
    _opacity_lr: 0.01
    _scaling_lr: 0.001
    _rotation_lr: 0.001
  loss_weights:
    rgb_loss: 1.0
    depth_loss: 0.2
    alpha_loss: 0.2  # 10.0
    normal_loss: 0.0 # 0.05
    dist_loss: 0.0

use_vis: False
vis:
  bev_w2c: [[-7.11877554e-01,  7.00066977e-01,  5.60051351e-02, -6.17312594e+01],
       [ 7.02237569e-01,  7.08450207e-01,  7.04322445e-02, 6.42232503e+01],
       [ 9.63043899e-03,  8.94680438e-02, -9.95943133e-01, 2.20510302e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.00000000e+00]]
  bev_intrinsic_dict:
    H: 1480
    W: 1920
    fu: 935
    fv: 935.44725606860459
    cu: 740 # cy
    cv: 959.5 # cx
  pose_scale: 1.0


use_metric: False

# 2024/10/01
use_storage_manager: True
storage_manager:
  distance_threshold: 80.0