use_wandb: False
use_sky: False
use_dynamic: False
use_metric: False
use_loop: True
debug_mode: True

mode: 'vio' # 'vo' or 'vio'

device:
  tracker: 'cuda:0'
  mapper: 'cuda:0'

dataset:
  root: /data/wuke/DATA/2024/RAW_KITTI/2011_10_03/2011_10_03_drive_0027partial_sync/
  module: datasets.kitti_sync
  rgb_strip: 1
  imu_delay: 0.07 # 0.072

middleware:
  cov_times: 1200000
  max_cov: 3e7
  max_depth: 25

output:
  save_dir: /data/wuke/workspace/VINGS-Mono/output/

# 9.601149e+02 0.000000e+00 6.947923e+02 0.000000e+00 9.548911e+02 2.403547e+02 0.000000e+00 0.000000e+00 1.000000e+00
intrinsic:
  H: 376
  W: 1241
  fu: 718.856
  fv: 718.856
  cu: 185.2157
  cv: 607.1928
  bg: 0

frontend:
  weight: /data/wuke/workspace/VINGS-Mono/ckpts/droid.pth
  image_size: [344, 616]
  buffer: 80
  filter_thresh: 2.4
  c2i: None
  visual_only: 0 # 0 means VIO and 1 means VO.
  warm_up: 8
  beta: 0.3
  frontend_nms: 1
  keyframe_thresh: 2.0
  frontend_window: 5
  frontend_thresh: 16.0 
  frontend_radius: 2
  active_window: 12
  # CovisibleGraph
  max_factors: 48
  far_threshold: 0.02
  inac_range: 3
  mask_threshold: -1.0
  skip_edge: [-4,-5,-6]
  translation_threshold: 0.5
  # Vis.
  show_plot: False

adc_args:
  accum_thresh: 0.98
training_args:
  num_keyframe: 8
  iters: 100
  lr: # Copy form 2DGS.
    _xyz_lr: 0.00002
    _rgb_lr: 0.0003
    _opacity_lr: 0.05
    _scaling_lr: 0.001
    _rotation_lr: 0.001
  loss_weights:
    rgb_loss: 1.0
    depth_loss: 1.0
    alpha_loss: 0.2  # 10.0
    normal_loss: 0.2 # 0.05
    dist_loss: 0.0

use_vis: False


looper:
  lightglue_weight_dir: /data/wuke/workspace/LightGlue-ONNX/weights/
  onnx_w: 512
  H: 344
  W: 616
  # nearest_k_frame: 10
  loop_radius: 15
  is_loop_min_match_num: 50
  search_num: 30
  is_loop_mse_threshold: 0.17 # 0.18
  is_loop_med_times: 100.0


use_storage_manager: False
storage_manager:
  distance_threshold: 120.0